/*
================================================
MAGNITUDE ANALYSIS
================================================
SCRIPT PURPOSE:
     This script compares key measure values across different business dimensions
     to understand the scale and distribution of the data. It breaks down customer
     counts by country and gender, product counts and average costs by category,
     total revenue by product category, total revenue contributed by each individual
     customer, and the distribution of sold item quantities across countries.

NOTE:
     Magnitude analysis helps identify which segments, regions, or categories
     drive the most volume or revenue. Results are ordered by the measure value
     in descending order to surface the highest-performing segments first.
*/

 -- ===================================
 -- MAGNITUDE: COMPARE THE MEASURE VALUES BY CATEGORIES.
 -- ===================================

 --FIND THE TOTAL NUMBER OF CUSTOMERS BY COUNTRIES

SELECT 
  COUNTRY,
  COUNT(CUSTOMER_KEY) AS total_customers
From gold.dim_customers
  GROUP BY country
  ORDER BY total_customers DESC;

-- FIND THE TOTAL CUSTOMERS BY GENDER

SELECT 
  gender,
  COUNT(CUSTOMER_KEY) AS total_customers
From gold.dim_customers
  GROUP BY gender
  ORDER BY total_customers DESC;

 -- FIND THE TOTAL PRODUCTS BY CATEGORY

SELECT 
  category,
  COUNT(product_key) AS total_products
From gold.dim_product
  GROUP BY category
  ORDER BY total_products DESC;

 -- WHAT IS THE AVERAGE COSTS IN EACH CATEGORY?

SELECT 
  category,
  AVG(cost) AS avg_costs
From gold.dim_product
  GROUP BY category
  ORDER BY avg_costs DESC;

 -- WHAT IS THE TOTAL REVENUE GENERATED FOR EACH CATEGORY?

SELECT 
  p.category,
  SUM(f.sales_amount) total_revenue
From gold.fact_sales f
left join gold.dim_product p
on p.product_key = f.product_key
  GROUP BY p.category
  ORDER BY total_revenue DESC;

 -- FIND TOTAL REVENUE IS GENERATED BY EACH CUSTOMER

SELECT 
  c.customer_key,
  c.first_name,
  c.last_name,
  SUM(f.sales_amount) as total_revenue
From gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
  GROUP BY 
  c.customer_key,
  c.first_name,
  c.last_name
  ORDER BY total_revenue DESC;

 -- WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES?

SELECT 
  c.country,
  SUM(f.quantity) total_sold_items
From gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.product_key
  GROUP BY 
  c.country
  ORDER BY total_sold_items DESC;
